### ISSUE TITLE
rainbow-delimiters-mode doesn't work well with htmlize

### ISSUE THREAD

**Issue by Dewdrops** [jlr/rainbow-delimiters#16] opened 2013-06-07 09:34 UTC
if you call htmlize-buffer in an buffer with rainbow-delimeters-mode enabled, you'll get error like 'eq: Wrong type argument: listp, "rainbow-delimiters-depth-9-face"'.

**Comment by jiyoo** [comment] 2013-08-25 19:09
This seems to be caused by the fact that rainbow-delimiters-depth-face returns a string rather than a symbol.

**Comment by Fanael** [comment] 2013-10-15 11:18
Fixed in ee4519d20a.

**Closed as completed by Fanael** 2013-10-15 11:18 UTC
