### ISSUE TITLE
A closing paren is sometimes highlighted in red on C mode

### ISSUE THREAD

**Issue by namikister** [jlr/rainbow-delimiters#25] opened 2014-02-09 07:55 UTC
A closing paren is sometimes highlighted in red with C or C++ mode.  The problem tend to happen on a large-sized file, so I cannot paste the example in this report.  But you can check the problem, for example at the line 1001 of src/eval.c in the emacs repository.

Just for your information, I tried to replace the function syntax-ppss with the function parse-partial-sexp in the rainbow-delimiters.el, and the problem seemed to disappear.

**Comment by Fanael** [comment] 2014-02-26 17:58
The problem is that changing `syntax-ppss` to `parse-partial-sexp` noticeably slows down scrolling big buffers with rainbow-delimiters enabled.

On my machine, scrolling to the middle of `src/xdisp.c` takes about a second when using `syntax-ppss` and about ten seconds when using `parse-partial-sexp`.

@jlr, @purcell: any idea how to deal with this? Perhaps caching the `parse-partial-sexp` calls on our own instead of relying on `syntax-ppss`?

**Comment by opsound** [comment] 2014-03-06 20:32
I work on large C files and have noticed the same red closing paren issue.

**Comment by Fanael** [comment] 2014-03-29 11:34
Untested fix that I hope doesn't degrade performance too much:

```
 diff --git a/rainbow-delimiters.el b/rainbow-delimiters.el
 --- a/rainbow-delimiters.el
 +++ b/rainbow-delimiters.el
 @@ -312,6 +312,24 @@ For example: 'rainbow-delimiters-depth-1-face'."

  ;;; Nesting level

 +(defvar rainbow-delimiters-parse-partial-sexp-cache nil)
 +(make-variable-buffer-local 'rainbow-delimiters-parse-partial-sexp-cache)
 +
 +(defun rainbow-delimiters-syntax-ppss-flush-cache (beg _end)
 +  (when (and rainbow-delimiters-parse-partial-sexp-cache
 +             (<= beg (car rainbow-delimiters-parse-partial-sexp-cache)))
 +    (setq rainbow-delimiters-parse-partial-sexp-cache nil)))
 +
 +(defsubst rainbow-delimiters-syntax-ppss (pos)
 +  (save-excursion
 +    (let* ((cache rainbow-delimiters-parse-partial-sexp-cache)
 +           (ppss (if (and cache (>= pos (car cache)))
 +                     (parse-partial-sexp (car cache) pos nil nil (cdr cache))
 +                   (parse-partial-sexp (point-min) pos))))
 +      (setq rainbow-delimiters-parse-partial-sexp-cache (cons pos ppss))
 +      (add-hook 'before-change-functions 'rainbow-delimiters-syntax-ppss-flush-cache t t)
 +      ppss)))
 +
  (defvar rainbow-delimiters-syntax-table nil
    "Syntax table (inherited from buffer major-mode) which uses all delimiters.

 @@ -336,7 +354,7 @@ major-mode. The syntax table is constructed by the function
    "Return # of nested levels of parens, brackets, braces LOC is inside of."
    (let ((depth
           (with-syntax-table rainbow-delimiters-syntax-table
 -           (car (syntax-ppss loc)))))
 +           (car (rainbow-delimiters-syntax-ppss loc)))))
      (if (>= depth 0)
          depth
        0))) ; ignore negative depths created by unmatched closing parens.
 @@ -433,7 +451,7 @@ Returns t if char at loc meets one of the following conditions:
  - Inside a string.
  - Inside a comment.
  - Is an escaped char, e.g. ?\)"
 -  (let ((parse-state (syntax-ppss loc)))
 +  (let ((parse-state (rainbow-delimiters-syntax-ppss loc)))
      (or
       (nth 3 parse-state)                ; inside string?
       (nth 4 parse-state)                ; inside comment?
```

@namikister, @opsound: can you please test whether this patch solves the issue?

**Comment by namikister** [comment] 2014-03-29 13:58
Thanks @Fanael.
I have tested the patch with a few large files.  It looks good so far.

**Comment by Fanael** [comment] 2014-03-29 16:16
In this case, fixed, I guess.

**Closed as completed by Fanael** 2014-03-29 16:16 UTC
