### ISSUE TITLE
Conflicting colouring with non-prog modes

### ISSUE THREAD

**Issue by edran** [jlr/rainbow-delimiters#31] opened 2014-08-28 13:19 UTC
Rainbow-delimiters deactivates colours in modes like magit-status and eshell.

Version: 

```
;; Version: 20140827.1040
;; X-Original-Version: 1.3.7
```

**Comment by tanzoniteblack** [comment] 2014-08-28 15:12
Also effecting me in modes like https://github.com/clojure-emacs/cider as well as in https://github.com/magit/magit

**Comment by Fanael** [comment] 2014-08-28 16:48
Can you provide a screenshot of what it looks like with and without `rainbow-delimiters` enabled?

**Comment by edran** [comment] 2014-08-28 17:05
There we go. Disabling the mode does not bring back the colours either (maybe some conflict with font-lock?)
![selection_044](https://cloud.githubusercontent.com/assets/3375046/4079439/3e12b6dc-2ed5-11e4-8b8c-92a940544efd.png)
![selection_045](https://cloud.githubusercontent.com/assets/3375046/4079458/5b8537bc-2ed5-11e4-8a1e-4da19cb8ead2.png)

**Comment by tanzoniteblack** [comment] 2014-08-28 17:05
With rainbow delimiters turned off:
![no-rainbow-delim](https://cloud.githubusercontent.com/assets/1134611/4079468/6c27b40a-2ed5-11e4-8de1-a8f296306f67.png)

With rainbow delimiters master
![rainbow-delim-master](https://cloud.githubusercontent.com/assets/1134611/4079466/6c2430d2-2ed5-11e4-82f3-d0297cc0e1c1.png)

With rainbow delimiters 1.3.6
![rainbow-delim-1 3 6](https://cloud.githubusercontent.com/assets/1134611/4079467/6c25fb92-2ed5-11e4-94be-6f2a98f8a14d.png)

**Comment by Fanael** [comment] 2014-08-28 17:31
What does `(when font-lock-mode (font-lock-fontify-buffer) t)` evaluate to in these buffers? Is highlighting lost when you eval this expression? If it is, then IMO it's a bug in these packages in that their own highlighting conflicts with `font-lock-mode` and they should fix it either by making their highlighting cooperate with `font-lock-mode` or by disabling `font-lock-mode` in these buffers.

I have an idea for a workaround, but I have to try it first.

**Comment by edran** [comment] 2014-08-28 17:32
It evaluates `t` to me (at least in the eshell buffer).

**Comment by tanzoniteblack** [comment] 2014-08-28 17:33
Evaluates to `t` for me as well, and screws up the coloring of the buffer the same as what I'm seeing with rainbow-delimiters

**Comment by purcell** [comment] 2014-08-28 17:58
At first glance, `magit-status-mode` seems to be doing things in a reasonable way: it doesn't specify any `font-lock` settings, it derives from `special-mode`, and it just marks up all its text with `'face` properties.

So when `rainbow-delimiters` runs there and calls `font-lock-flush` or `font-lock-fontify-buffer`, the basic `font-lock-defaults` are blank, and of course the pre-existing fontification is undone: `font-lock` always ignores and replaces existing `face` properties.

Not sure what the best solution is, or if there is one, but just wanted to add this info to the discussion.

**Comment by Fanael** [comment] 2014-08-28 17:59
Not a `rainbow-delimiters` bug IMO then, please try raising the issue at the bug trackers of the respective packages.

You can try this workaround, but I'm reluctant to apply it as it essentially reverts c4c127992, meaning #5 is broken again. Of course, it's WIP and may eat your guinea pig.

Or, possibly, stop using `global-rainbow-delimiters-mode`. Frankly, I think that modes that go anywhere near syntax highlighting should never have a globalized forms because of possibility of breaking modes that never expected other modes to touch their buffers. Like this very bug. Unfortunately, I can't remove `global-rainbow-delimiters-mode` now since so many people use it.

```
 rainbow-delimiters.el | 99 ++++++++++++++++++++++++++-------------------------
 1 file changed, 51 insertions(+), 48 deletions(-)

diff --git a/rainbow-delimiters.el b/rainbow-delimiters.el
index 6d8c2fa..6624575 100644
--- a/rainbow-delimiters.el
+++ b/rainbow-delimiters.el
@@ -438,7 +438,7 @@ MATCH is nil iff it's a mismatched closing delimiter."
                                             depth
                                             match)))

-;;; Font-Lock functionality
+;;; Jit-Lock functionality

 (defconst rainbow-delimiters-delim-regex "\\(\(\\|\)\\|\\[\\|\\]\\|\{\\|\}\\)"
   "Regex matching all opening and closing delimiters the mode highlights.")
@@ -458,53 +458,59 @@ DELIMITER is the closing delimiter.
 OPENING is the corresponding opening delimiter.
 TYPE is the delimiter type string for `rainbow-delimiters-apply-color'.")

-;; Main function called by font-lock.
-(defun rainbow-delimiters-propertize (end)
-  "Highlight delimiters in region between point and END.
+;; Main function called by jit-lock.
+(defun rainbow-delimiters-propertize (start end)
+  "Highlight delimiters in region between START and END.

-Used by font-lock for dynamic highlighting."
+Used by jit-lock for dynamic highlighting."
   (setq rainbow-delimiters-escaped-char-predicate
         (cdr (assoc major-mode rainbow-delimiters-escaped-char-predicate-list)))
-  (with-syntax-table rainbow-delimiters-syntax-table
-    (let ((inhibit-point-motion-hooks t))
-      ;; Point can be anywhere in buffer; determine the nesting depth at point.
-      (let ((depth (rainbow-delimiters-depth (point))))
-        (while (and (< (point) end)
-                    (re-search-forward rainbow-delimiters-delim-regex end t))
-          (let ((delim-pos (match-beginning 0)))
-            (let ((ppss (rainbow-delimiters-syntax-ppss delim-pos)))
-              (unless (rainbow-delimiters-char-ineligible-p delim-pos ppss)
-                (let* ((delim (char-after delim-pos))
-                       (opening-delim-info
-                        (assq delim rainbow-delimiters-opening-delim-info)))
-                  (if opening-delim-info
-                      (progn
-                        (setq depth (1+ depth))
-                        (rainbow-delimiters-apply-color (cdr opening-delim-info)
+  (save-excursion
+    (with-syntax-table rainbow-delimiters-syntax-table
+      (let ((inhibit-point-motion-hooks t))
+        (goto-char start)
+        ;; Start can be anywhere in buffer; determine the nesting depth at start.
+        (let ((depth (rainbow-delimiters-depth start)))
+          (while (and (< (point) end)
+                      (re-search-forward rainbow-delimiters-delim-regex end t))
+            (let ((delim-pos (match-beginning 0)))
+              (let ((ppss (rainbow-delimiters-syntax-ppss delim-pos)))
+                (unless (rainbow-delimiters-char-ineligible-p delim-pos ppss)
+                  (let* ((delim (char-after delim-pos))
+                         (opening-delim-info
+                          (assq delim rainbow-delimiters-opening-delim-info)))
+                    (if opening-delim-info
+                        (progn
+                          (setq depth (1+ depth))
+                          (rainbow-delimiters-apply-color (cdr opening-delim-info)
+                                                          depth
+                                                          delim-pos
+                                                          t))
+                      ;; Not an opening delimiter, so it's a closing delimiter.
+                      (let ((closing-delim-info
+                             (assq delim rainbow-delimiters-closing-delim-info))
+                            (matching-opening-delim (char-after (nth 1 ppss))))
+                        (rainbow-delimiters-apply-color (nthcdr 2 closing-delim-info)
                                                         depth
                                                         delim-pos
-                                                        t))
-                    ;; Not an opening delimiter, so it's a closing delimiter.
-                    (let ((closing-delim-info
-                           (assq delim rainbow-delimiters-closing-delim-info))
-                          (matching-opening-delim (char-after (nth 1 ppss))))
-                      (rainbow-delimiters-apply-color (nthcdr 2 closing-delim-info)
-                                                      depth
-                                                      delim-pos
-                                                      (= (nth 1 closing-delim-info)
-                                                         matching-opening-delim))
-                      (setq depth (or (and (<= depth 0) 0) ; unmatched delim
-                                      (1- depth)))))))))))))
-  ;; We already fontified the delimiters, tell font-lock there's nothing more
-  ;; to do.
-  nil)
+                                                        (= (nth 1 closing-delim-info)
+                                                           matching-opening-delim))
+                        (setq depth (or (and (<= depth 0) 0) ; unmatched delim
+                                        (1- depth)))))))))))))))

-;;; Minor mode:
+(defun rainbow-delimiters-unpropertize ()
+  "Remove highlighting from delimiters in the current buffer."
+  (save-excursion
+    (save-restriction
+      (with-silent-modifications
+        (let ((inhibit-point-motion-hooks t))
+          (widen)
+          (goto-char (point-min))
+          (while (and (not (eobp))
+                      (re-search-forward rainbow-delimiters-delim-regex nil t))
+            (remove-text-properties (match-beginning 0) (match-end 0) '(face nil))))))))

-;; NB: no face defined here because we apply the faces ourselves instead of
-;; leaving that to font-lock.
-(defconst rainbow-delimiters-font-lock-keywords
-  '(rainbow-delimiters-propertize))
+;;; Minor mode:

 (defun rainbow-delimiters-mode-turn-on ()
   "Set up `rainbow-delimiters-mode'."
@@ -512,8 +518,7 @@ Used by font-lock for dynamic highlighting."
   (setq rainbow-delimiters-parse-partial-sexp-cache nil)
   (add-hook 'before-change-functions 'rainbow-delimiters-syntax-ppss-flush-cache t t)
   (add-hook 'change-major-mode-hook 'rainbow-delimiters-mode-turn-off nil t)
-  (font-lock-add-keywords nil rainbow-delimiters-font-lock-keywords 'append)
-  (set (make-local-variable 'jit-lock-contextually) t)
+  (jit-lock-register 'rainbow-delimiters-propertize t)
   ;; Create necessary syntax tables inheriting from current major-mode.
   (set (make-local-variable 'rainbow-delimiters-syntax-table)
        (rainbow-delimiters-make-syntax-table (syntax-table))))
@@ -521,7 +526,8 @@ Used by font-lock for dynamic highlighting."
 (defun rainbow-delimiters-mode-turn-off ()
   "Tear down `rainbow-delimiters-mode'."
   (kill-local-variable 'rainbow-delimiters-syntax-table)
-  (font-lock-remove-keywords nil rainbow-delimiters-font-lock-keywords)
+  (jit-lock-unregister 'rainbow-delimiters-propertize)
+  (rainbow-delimiters-unpropertize)
   (remove-hook 'change-major-mode-hook 'rainbow-delimiters-mode-turn-off t)
   (remove-hook 'before-change-functions 'rainbow-delimiters-syntax-ppss-flush-cache t))

@@ -531,10 +537,7 @@ Used by font-lock for dynamic highlighting."
   nil "" nil ; No modeline lighter - it's already obvious when the mode is on.
   (if rainbow-delimiters-mode
       (rainbow-delimiters-mode-turn-on)
-    (rainbow-delimiters-mode-turn-off))
-  (if (fboundp 'font-lock-flush)
-      (font-lock-flush)
-    (font-lock-fontify-buffer)))
+    (rainbow-delimiters-mode-turn-off)))

 ;;;###autoload
 (defun rainbow-delimiters-mode-enable ()
```

**Comment by Fanael** [comment] 2014-08-28 18:02
> At first glance, `magit-status-mode` seems to be doing things in a reasonable way: it doesn't specify any `font-lock` settings, it derives from `special-mode`, and it just marks up all its text with `'face` properties.

I think that the most reasonable way would be that, _and_ disabling `font-lock-mode`. This way, wrapping our `font-lock-flush` call in a `(when font-lock-mode …)`, which I accidentally forgot, would fix the problem entirely.

**Comment by Fanael** [comment] 2014-08-28 18:29
> Not sure what the best solution is, or if there is one.

Yeah. The way I see it, the only solution that won't break anything is to file bugs against third-party packages so they either disable `font-lock-mode` when they apply their own, incompatible, highlighting, or arrange it so `font-lock-flush` or `font-lock-fontify-buffer` won't break their highlighting.

The second best solution would be getting rid of `global-rainbow-delimiters-mode`. This is a user-visible API change, though, so we'd probably have to deprecate it first before ditching it completely.

A non-solution would be reverting c4c127992, as that breaks #5, or doing nothing.

…I have an idea for another workaround. It still _will_ break highlighting, but only the highlighting of delimiters.

**Comment by purcell** [comment] 2014-08-28 18:38
> Unfortunately, I can't remove global-rainbow-delimiters-mode now since so many people use it.

One backwards-compatible option would be to provide a customizable list of modes in which `global-rainbow-delimiters-mode` should not enable `rainbow-delimiters-mode`.  This way, we're not waiting for upstream fixes, even if they might be the right thing to do.

**Comment by Fanael** [comment] 2014-08-28 18:40
Go ahead and implement it, then. By the way, that's exactly what has been requested in #7, though for a very different reason.

**Comment by purcell** [comment] 2014-08-28 18:42
Cool, I'll do that.

**Comment by Fanael** [comment] 2014-08-28 18:52
> …I have an idea for another workaround. It still will break highlighting, but only the highlighting of delimiters.

No. Tested it, doesn't work. Flushing the highlighting only on the delimiters sounds promising, but `font-lock-mode` seems to highlight the whole line anyway.

Therefore, blacklisting problematic modes sounds like the best workaround, while waiting for upstreams to fix their part of the issue.

**Comment by purcell** [comment] 2014-08-28 18:58
Okay, 0fa4723 should do the trick. I'll leave this ticket open until the fix has been confirmed by those affected.

**Comment by Fanael** [comment] 2014-08-28 19:01
NB: Eshell is unaffected in 24.4.50.

![eshell](https://cloud.githubusercontent.com/assets/270470/4081289/423b235a-2ee6-11e4-98db-dd4787af9d05.png)

**Comment by purcell** [comment] 2014-08-28 19:06
Should we leave it out of the list, then?

**Comment by Fanael** [comment] 2014-08-28 19:08
I don't know. The OP's screen indicates Eshell being affected. I guess it's better to stay on the safe side, after all, `rainbow-delimiters` still supports Emacs **23**, and works even in **22.3**.

**Comment by edran** [comment] 2014-08-28 19:26
Oh, sorry - I'm currently using **24.3.1** FYI.

**Comment by gongzhitaao** [comment] 2014-08-31 21:39
I had similar issue with Gnus highlight.  I use the following code to hightlight the Gnus summary buffer,

``` elisp

(defun gnus-user-format-function-color-author (header)
  (let ((header-author-string
         (extract-author (mail-header-from header)))
        (age-level (header-age-level header)))
    (cond
      ((= 0 age-level)
       (propertize header-author-string
           'face 'my-author-one-day-old-face
           'gnus-face t))
      ((= 1 age-level)
       (propertize header-author-string
           'face 'my-author-one-week-old-face
           'gnus-face t))
      (t
       (propertize header-author-string
                   'face 'my-author-more-than-one-week-old-face
                   'gnus-face t)))))
```

When, `rainbow-delimiters-mode` is off, the hightlight works fine.

![tmp](https://cloud.githubusercontent.com/assets/704995/4103322/fb823322-3156-11e4-81c2-e88c5bace70e.png)

When enabled, the color goes away

![tmp2](https://cloud.githubusercontent.com/assets/704995/4103333/3065a6b4-3157-11e4-8a8e-4988ad3f9ffe.png)

**Comment by Fanael** [comment] 2014-08-31 22:27
@gongzhitaao: you brought it on yourself. You apply your own highlighting `font-lock-mode` has no clue about, so the correct _solution_ (as opposed to a workaround) is either disabling `font-lock-mode` in the buffer or making the highlighting compatible with `font-lock-mode`. The former is probably less work.
A workaround would be adding the relevant major mode to `rainbow-delimiters-ignore-modes`.

Or simply stop using `global-rainbow-delimiters-mode` because it's _impossible_ for it to work the way one may naïvely expect everywhere.

**Comment by gongzhitaao** [comment] 2014-09-01 12:52
@Fanael That makes much more sense.  Thanks for your explanation.  Although using Emacs for years, I'm new to the highlight thing in Emacs.

**Comment by Fanael** [comment] 2014-09-02 14:20
From the [Emacs manual](https://www.gnu.org/software/emacs/manual/html_node/elisp/Font-Lock-Basics.html):

> If your mode fontifies text explicitly by adding font-lock-face properties, it can specify (nil t) for font-lock-defaults to turn off all automatic fontification. However, this is not required; it is possible to fontify some things using font-lock-face properties and set up automatic fontification for other parts of the text.

This is probably the best way to handle it in upstream projects, even better than disabling `font-lock-mode`.

/cc @gongzhitaao

**Comment by Fanael** [comment] 2014-09-02 14:31
Therefore, it's definitely an upstream issue. Closing; please tell the upstream projects to use `font-lock-face` instead of `face`.

**Closed as completed by Fanael** 2014-09-02 14:31 UTC

**Comment by bbatsov** [comment] 2014-09-14 18:08
:+1: Wish someone made me aware of this issue earlier. CIDER is now updated as suggested!
